### ISSUE TITLE
Upgrading omniauth-oauth2

### ISSUE THREAD

**Issue by aguynamedben** [nitanshu/omniauth-dropbox-business-api2#1]
Thank you for taking the time to make this library public.

I'm also trying to use omniauth-google-oauth2, which requires omniauth-oauth2 >= 1.5. Bundler is unable to install a version of omniauth-oauth2 that meets this requirement because this library requires 1.3.1.

Should I try to upgrade this library to a new version of omniauth-oauth2? Do you anticipate any problems will arise if that is done?

```Resolving dependencies...
Bundler could not find compatible versions for gem "omniauth-oauth2":
  In snapshot (Gemfile.lock):
    omniauth-oauth2 (= 1.3.1)

  In Gemfile:
    omniauth-dropbox-business-api2 was resolved to 0.0.1, which depends on
      omniauth-oauth2 (~> 1.3.1)

    omniauth-google-oauth2 was resolved to 0.5.3, which depends on
      omniauth-oauth2 (>= 1.5)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.```

**Comment by nitanshu** [comment]
Updated the gemspec file now you can install it will not show any errors and final version is 0.0.3.

Please let me know if any more issues are there.

**Comment by aguynamedben** [comment]
@nitanshu Will try today, thank you!

**Comment by aguynamedben** [comment]
Addressed in https://github.com/nitanshu/omniauth-dropbox-business-api2/commit/af6f25cf7c8d104cc93790a3a63d3a7402ef01a3
